name: Telegram Notification

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}   # or secrets.TELEGRAM_CHAT_ID
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - name: Send Telegram message
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          ACTOR: ${{ github.actor }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="PR '$PR_TITLE' by $PR_USER was merged.\n$PR_URL"
          else
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="New push to main branch by $ACTOR"
          fi
