name: Telegram Notification

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        shell: bash
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_MERGED: ${{ github.event.pull_request.merged }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            if [ "$PR_MERGED" = "true" ]; then
              # Notification when PR is merged
              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d chat_id="${TELEGRAM_CHAT_ID}" \
                -d text="PR '${PR_TITLE}' by ${PR_USER} was merged.\n${PR_URL}"
            elif [ "${{ github.event.action }}" = "opened" ]; then
              # Notification when PR is opened
              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d chat_id="${TELEGRAM_CHAT_ID}" \
                -d text="New PR opened to main: '${PR_TITLE}' by ${PR_USER}.\n${PR_URL}"
            fi
          fi