name: Telegram Notification (Debug)

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets and env
        shell: bash
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          ACTOR: ${{ github.actor }}
        run: |
          echo "Event name: $EVENT_NAME"
          echo "Actor: $ACTOR"
          echo "PR title: $PR_TITLE"
          echo "PR user: $PR_USER"
          echo "PR URL: $PR_URL"
          echo "Length of TELEGRAM_CHAT_ID: ${#TELEGRAM_CHAT_ID}"
          echo "Length of TELEGRAM_BOT_TOKEN: ${#TELEGRAM_BOT_TOKEN}"
