name: Telegram Notification

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          ACTOR: ${{ github.actor }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            curl -s -X POST "https://api.telegram.org/bot8091548592:AAHhR-QoyXU_7GfQi97fjIJ_zd1STdB_FWY/sendMessage" \
              -d chat_id=-1002716703405 \
              -d text="PR '$PR_TITLE' by $PR_USER was merged.\n$PR_URL"
          else
            curl -s -X POST "https://api.telegram.org/bot8091548592:AAHhR-QoyXU_7GfQi97fjIJ_zd1STdB_FWY/sendMessage" \
              -d chat_id=-1002716703405 \
              -d text="New push to main branch by $ACTOR"
          fi
